## Solve these exercises in the codeblock below each question and compare your answer

1.How to import pandas and check the version?

2.Create a pandas series from each of the items below: a list, numpy and a dictionary Input

import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')

myarr = np.arange(26)

mydict = dict(zip(mylist, myarr))

a  &nbsp;  0

b  &nbsp;  1

c  &nbsp;  2

d  &nbsp;  4

e  &nbsp;  3

dtype: int64

3.Convert the series ser into a dataframe with its index as another column on the dataframe. Input

mylist = list('abcedfghijklmnopqrstuvwxyz')

myarr = np.arange(26)

mydict = dict(zip(mylist, myarr))

ser = pd.Series(mydict)

  index &nbsp; 0

0     a  0

1     b  1

2     c  2

3     d  4

4     e  3

4.Combine ser1 and ser2 to form a dataframe.

Input

import numpy as np

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser2 = pd.Series(np.arange(26)

&nbsp;  &nbsp;col1  col2

0  &nbsp;  a &nbsp;&nbsp;    0

1  &nbsp;  b &nbsp;&nbsp;    1

2  &nbsp;  c &nbsp;&nbsp;    2

3  &nbsp;  e &nbsp;&nbsp;    3

4  &nbsp;  d &nbsp;&nbsp;    4

5.Give a name to the series ser calling it ‘alphabets’.

Input

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

0    a

1    b

2    c

3    e

4    d

Name: alphabets, dtype: object

6.From ser1 remove items present in ser2.

ser1 = pd.Series([1, 2, 3, 4, 5])

ser2 = pd.Series([4, 5, 6, 7, 8])

0    1

1    2

2    3

dtype: int64

7.Get all items of ser1 and ser2 not common to both. Input

ser1 = pd.Series([1, 2, 3, 4, 5])

ser2 = pd.Series([4, 5, 6, 7, 8])

0 &nbsp;   1<br>
1  &nbsp;  2<br>
2  &nbsp;  3<br>
5  &nbsp;  6<br>
6  &nbsp;  7<br>
7  &nbsp;  8<br>
dtype: int64


8.Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

Input

ser = pd.Series(np.random.normal(10, 5, 25))

array([  1.39267584,   6.49135133,  10.2578186 ,  13.06985067,  25.80920994])

9.Calculte the frequency counts of each unique value ser.

 Input

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

f  &nbsp;  8<br>
g &nbsp;   7<br>
b &nbsp;   6<br>
c  &nbsp;  4<br>
a  &nbsp;  2<br>
e  &nbsp;  2<br>
h  &nbsp;  1<br>
dtype: int64

10.From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

 Input

np.random.RandomState(100)


ser = pd.Series(np.random.randint(1, 5, [12]))

Top&nbsp; 2 Freq:&nbsp; 4&nbsp;    5<br>
3  &nbsp;  3<br>
2  &nbsp;  2<br>
1  &nbsp;  2<br>
dtype: int64<br><br>

0  &nbsp;   Other<br>
1  &nbsp;   Other<br>
2  &nbsp;       3<br>
3  &nbsp;       4<br>
4  &nbsp;   Other<br>
5  &nbsp;       4<br>
6  &nbsp;       4<br>
7  &nbsp;       3<br>
8  &nbsp;       3<br>
9  &nbsp;       4<br>
10 &nbsp;       4<br>
11 &nbsp;   Other<br>
dtype:&nbsp; object<br>

11.Bin the series ser into 10 equal deciles and replace the values with the bin name.

Input

ser = pd.Series(np.random.random(20))

0 &nbsp;   0.556912

1 &nbsp;    0.892955

2 &nbsp;    0.566632

3 &nbsp;    0.146656

4 &nbsp;    0.881579

dtype: float64


0 &nbsp;   7th

1 &nbsp;   9th

2 &nbsp;   7th

3 &nbsp;   3rd

4 &nbsp;   8th

dtype: category

Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

12. Reshape the series ser into a dataframe with 7 rows and 5 columns

Input

ser = pd.Series(np.random.randint(1, 10, 35))

   0  1  2  3  4

0  1  2  1  2  5

1  1  2  4  5  2

2  1  3  3  2  8

3  8  6  4  9  6

4  2  1  1  8  5

5  3  2  8  5  6

6  1  5  5  4  6

13.Find the positions of numbers that are multiples of 3 from ser.

 Input

ser = pd.Series(np.random.randint(1, 10, 7))

0    6

1    8

2    6

3    7

4    6

5    2

6    4

dtype: int64

array([[0],<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2],<br>
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[4]])

14.From ser, extract the items at positions in list pos.

 Input

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

pos = [0, 4, 8, 14, 20]

0     a<br>
4     e<br>
8     i<br>
14    o<br>
20    u<br>
dtype: object

15.Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

Input

ser1 = pd.Series(range(5))

ser2 = pd.Series(list('abcde'))

 &nbsp;&nbsp;  0  1<br>
0  0  a<br>
1  1  b<br>
2  2  c<br>
3  3  d<br>
4  4  e<br>

16.Get the positions of items of ser2 in ser1 as a list.

Input

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])

ser2 = pd.Series([1, 3, 10, 13])

[5, 4, 0, 8]

17.Compute the mean squared error of truth and pred series.

 Input

truth = pd.Series(range(10))

pred = pd.Series(range(10)) + np.random.random(10)

0.28448128110629545

18.Change the first character of each word to upper case in each word of ser.

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

0     How<br>
1      To<br>
2    Kick<br>
3    Ass?<br>
dtype: object

19.Calculate the number of characters in each word in a series?

Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

0    3<br>
1    2<br>
2    4<br>
3    4<br>
dtype: int64

20.Difference of differences between the consequtive numbers of ser.

 Input

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

21.convert a series of date-strings to a timeseries

 Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

0   2010-01-01 00:00:00

1   2011-02-02 00:00:00

2   2012-03-03 00:00:00

3   2013-04-04 00:00:00

4   2014-05-05 00:00:00

5   2015-06-06 12:20:00

dtype: datetime64[ns]

22.Get the day of month, week number, day of year and day of week from ser.

Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

Date:  [1, 2, 3, 4, 5, 6]

Week number:  [53, 5, 9, 14, 19, 23]

Day num of year:  [1, 33, 63, 94, 125, 157]

Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

23.Change ser to dates that start with 4th of the respective months.

Input

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

0   2010-01-04

1   2011-02-04

2   2012-03-04

dtype: datetime64[ns]

24.From ser, extract words that contain atleast 2 vowels.

 Input

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

0     Apple

1    Orange

4     Money

dtype: object

25. Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.

Input

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

1    rameses@egypt.com

2            matt@t.co

3    narendra@modi.com

dtype: object

26.Compute the mean of weights of each fruit.
<br> Input

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))<br>
weights = pd.Series(np.linspace(1, 10, 10))<br>
print(weight.tolist())<br>
print(fruit.tolist())<br>
> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]<br>
> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']



values can change due to randomness

apple     6.0

banana    4.0

carrot    5.8

dtype: float64

27.Compute the euclidean distance between series (points) p and q, without using a packaged formula.<br> Input<br>

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])<br>
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

18.165

28.Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

 Input

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

array([1, 5, 7])

29.Replace the spaces in my_str with the least frequent character.

Input

my_str = 'dbc deb abed gade'

'dbccdebcabedcgade'  # least frequent is 'c'

30.create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

 values can be random

2000-01-01   &nbsp;4

2000-01-08    &nbsp;1

2000-01-15    &nbsp;8

2000-01-22    &nbsp;4

2000-01-29    &nbsp;4

2000-02-05    &nbsp;2

2000-02-12    &nbsp;4

2000-02-19    &nbsp;9

2000-02-26    &nbsp;6

2000-03-04    &nbsp;6

31.ser has missing dates and values. Make all missing dates appear and fill up with value from previous date. <br>Input<br>

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))<br>
print(ser)<br>
> 2000-01-01     1.0<br>
> 2000-01-03    10.0<br>
> 2000-01-06     3.0<br>
> 2000-01-08     NaN<br>
> dtype: float64

2000-01-01     1.0<br>
2000-01-02     1.0<br>
2000-01-03    10.0<br>
2000-01-04    10.0<br>
2000-01-05    10.0<br>
2000-01-06     3.0<br>
2000-01-07     3.0<br>
2000-01-08     NaN

32.Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.<br> Input<br>

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

 values will change due to randomness<br>
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]<br>
Lag having highest correlation:  9

33.Import every 50th row of BostonHousing dataset as a dataframe. <br>
URL:https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv

                  crim    zn  indus chas                  nox     rm   age  
0              0.21977   0.0   6.91    0  0.44799999999999995  5.602  62.0   
1               0.0686   0.0   2.89    0                0.445  7.416  62.5   
2   2.7339700000000002   0.0  19.58    0                0.871  5.597  94.9   
3               0.0315  95.0   1.47    0  0.40299999999999997  6.975  15.3   
4  0.19072999999999998  22.0   5.86    0                0.431  6.718  17.5   

     dis rad  tax ptratio       b  lstat  medv  
0  6.0877   3  233    17.9   396.9   16.2  19.4  
1  3.4952   2  276    18.0   396.9   6.19  33.2  
2  1.5257   5  403    14.7  351.85  21.45  15.4  
3  7.6534   3  402    17.0   396.9   4.56  34.9  
4  7.8265   7  330    19.1  393.74   6.56  26.2  

34.Import the boston housing dataset, but while importing change the 'medv' (median house value) column so that values < 25 becomes ‘Low’ and > 25 becomes ‘High’.

URL:https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv

array([[ 0,  1,  2,  3],<br>
       [ 2,  3,  4,  5],<br>
       [ 4,  5,  6,  7],<br>
       [ 6,  7,  8,  9],<br>
       [ 8,  9, 10, 11],<br>
       [10, 11, 12, 13]])

35.create a dataframe with rows as strides from a given series?

 Input

L = pd.Series(range(15))

array([[ 0,  1,  2,  3],<br>
       [ 2,  3,  4,  5],<br>
       [ 4,  5,  6,  7],<br>
       [ 6,  7,  8,  9],<br>
       [ 8,  9, 10, 11],<br>
       [10, 11, 12, 13]])

36.Import ‘crim’ and ‘medv’ columns of the BostonHousing dataset as a dataframe.

URL:https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv

      crim  medv
0  0.00632  24.0<br>
1  0.02731  21.6<br>
2  0.02729  34.7<br>
3  0.03237  33.4<br>
4  0.06905  36.2

37.Get the number of rows, columns, datatype and summary statistics of each column of the Cars93 dataset. Also get the numpy array and list equivalent of the dataframe.

URL:https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv

(93, 27)<br>
Manufacturer           object<br>
Model                  object<br>
Type                   object<br>
Min.Price             float64<br>
Price                 float64<br>
Max.Price             float64<br>
MPG.city              float64<br>
MPG.highway           float64<br>
AirBags                object<br>
DriveTrain             object<br>
Cylinders              object<br>
EngineSize            float64<br>
Horsepower            float64<br>
RPM                   float64<br>
Rev.per.mile          float64<br>
Man.trans.avail        object<br>
Fuel.tank.capacity    float64<br>
Passengers            float64<br>
Length                float64<br>
Wheelbase             float64<br>
Width                 float64<br>
Turn.circle           float64<br>
Rear.seat.room        float64<br>
Luggage.room          float64<br>
Weight                float64<br>
Origin                 object<br>
Make                   object<br>
dtype: object<br>
float64    18<br>
object      9<br>
dtype: int64<br>
float64    18<br>
object      9<br>
dtype: int64

38.extract the row and column number of a particular cell with given criterion?

 Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

61.899999999999999

39.Rename the column Type as CarType in df and replace the ‘.’ in column names with ‘_’. Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.columns)

> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
>        'Make'],
>       dtype='object')

print(df.columns)
> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
>        'Make'],
>       dtype='object')

40.Check if df has any missing values.

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

true

41. Count the number of missing values in each column of df. Which column has the maximum number of missing values?

 Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')



'Luggage.room'

42.Replace missing values in Min.Price and Max.Price columns with their respective mean.

 Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

   Min.Price  Max.Price<br>
0  12.900000  18.800000<br>
1  29.200000  38.700000<br>
2  25.900000  32.300000<br>
3  17.118605  44.600000<br>
4  17.118605  21.459091

43.In df, use apply method to replace the missing values in Min.Price with the column’s mean and those in Max.Price with the column’s median.

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

44.Get the first column (a) in df as a dataframe (rather than as a Series).

Input

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

45.    In df, interchange columns 'a' and 'c'.

    Create a generic function to interchange two columns, without hardcoding column names.
    
    Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.

Input

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

46.Change the pamdas display settings on printing the dataframe df it shows a maximum of 10 rows and 10 columns.

 Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

47.Suppress scientific notations like ‘e-03’ in df and print upto 4 numbers after decimal.

 Input

df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

df

>          random
> 0  3.474280e-03<br>
> 1  3.951517e-05<br>
> 2  7.469702e-02<br>
> 3  5.541282e-28

>    random<br>
> 0  0.0035<br>
> 1  0.0000<br>
> 2  0.0747<br>
> 3  0.0000

48.Format the values in column 'random' of df as percentages.

 Input

df = pd.DataFrame(np.random.random(4), columns=['random'])

df

>      random
> 0    .689723<br>
> 1    .957224<br>
> 2    .159157<br>
> 3    .21082

>      random
> 0    68.97%<br>
> 1    95.72%<br>
> 2    15.91%<br>
> 3    2.10%

49.From df, filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

 Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')



>   &nbsp;&nbsp;&nbsp;Manufacturer    Model     Type<br>
0         Acura  Integra    Small<br>
20     Chrysler  LeBaron  Compact<br>
40        Honda  Prelude   Sporty<br>
60      Mercury   Cougar  Midsize<br>
80       Subaru   Loyale    Small

50.In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

Manufacturer    Model     Type  Min.Price  Max.Price<br>
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8<br>
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7<br>
Audi_90_Compact                Audi       90  Compact       25.9       32.3<br>
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6<br>
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN

51.Find the row position of the 5th largest value of column 'a' in df.

Input

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

 &nbsp;&nbsp;&nbsp;a&nbsp;&nbsp;b&nbsp;&nbsp;   c<br>
0  27   7  25<br>
1   8   4  20<br>
2   1   7  17<br>
3  24   9  17<br>
4  21  15   9<br>
5  21  16  20<br>
6  19  27  25<br>
7  12   8  20<br>
8  11  16  28<br>
9  24  13   4<br>

4

52.In ser, find the position of the 2nd largest value greater than the mean.

Input

ser = pd.Series(np.random.randint(1, 100, 15))

ser:  [7, 77, 16, 86, 60, 38, 34, 36, 83, 27, 16, 52, 50, 52, 54] mean:  46

array([3])


53.Get the last two rows of df whose row sum is greater than 100.

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;   1&nbsp;&nbsp;&nbsp;   2&nbsp;&nbsp;   3<br>
10  27  35  18  21<br>
11  37  26  15  23


54.Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value.

Input

ser = pd.Series(np.logspace(-2, 2, 30))

0.05 %ile:  0.016049294077 | 0.95 %ile:  63.8766722202

55.Reshape df to the largest possible square with negative values removed. Drop the smallest values if need be. The order of the positive numbers in the result should remain the same as the original.

Input

df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

    0   1   2   3   4   5   6   7   8   9
0  25 -13  17  16   0   6  22  44  10 -19<br>
1  47   4  -1  29 -13  12  41 -13  49  42<br>
2  20 -20   9  16 -17  -1  37  39  41  37<br>
3  27  44  -5   5   3 -12   0 -13  23  45<br>
4   8  27  -8  -3  48 -16  -5  40  16  10<br>
5  12  12  41 -12   3 -17  -3  27 -15  -1<br>
6  -9  -3  41 -13   1   0  28  33  -2  18<br>
7  18 -14  35   5   4  14   4  44  14  34<br>
8   1  24  26  28 -10  17 -14  14  38  17<br>
9  13  12   5   9 -16  -7  12 -18   1  24<br>
[[ 25.  17.  16.   6.  22.  44.  10.  47.]<br>
 [  4.  29.  12.  41.  49.  42.  20.   9.]<br>
 [ 16.  37.  39.  41.  37.  27.  44.   5.]<br>
 [  3.  23.  45.   8.  27.  48.  40.  16.]<br>
 [ 10.  12.  12.  41.   3.  27.  41.  28.]<br>
 [ 33.  18.  18.  35.   5.   4.  14.   4.]<br>
 [ 44.  14.  34.  24.  26.  28.  17.  14.]<br>
 [ 38.  17.  13.  12.   5.   9.  12.  24.]]<br>

56.Swap rows 1 and 2 in df.

 Input

df = pd.DataFrame(np.arange(25).reshape(5, -1))

&nbsp;&nbsp;&nbsp;    0&nbsp;&nbsp;   1&nbsp;&nbsp;   2&nbsp;&nbsp;   3&nbsp;&nbsp;&nbsp;   4<br>
4  20  21  22  23  24<br>
3  15  16  17  18  19<br>
2  10  11  12  13  14<br>
1 &nbsp;&nbsp;  5&nbsp;   6&nbsp;   7&nbsp;&nbsp;&nbsp;   8&nbsp;&nbsp;&nbsp;   9<br>
0 &nbsp;&nbsp;  0&nbsp;   1&nbsp;   2&nbsp;&nbsp;&nbsp;   3&nbsp;&nbsp;&nbsp;   4<br>

57.Reverse all the rows of dataframe df.

 Input

df = pd.DataFrame(np.arange(25).reshape(5, -1))

&nbsp;&nbsp;    0&nbsp;&nbsp;   1&nbsp;&nbsp;   2&nbsp;&nbsp;&nbsp;   3&nbsp;&nbsp;&nbsp;   4<br>
4  20  21  22  23  24<br>
3  15  16  17  18  19<br>
2  10  11  12  13  14<br>
1  &nbsp; 5&nbsp;&nbsp;&nbsp;   6&nbsp;&nbsp;   7&nbsp;&nbsp;   8&nbsp;&nbsp;   9<br>
0&nbsp;   0&nbsp;&nbsp;&nbsp;   1&nbsp;&nbsp;   2&nbsp;&nbsp;   3&nbsp;&nbsp;&nbsp;   4<br>

58. Get one-hot encodings for column 'a' in the dataframe df and append it as columns.

Input

df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

&nbsp;&nbsp;    a&nbsp;&nbsp;&nbsp;   b&nbsp;&nbsp;   c&nbsp;&nbsp;   d&nbsp;&nbsp;   e

0   0&nbsp;&nbsp;&nbsp;   1&nbsp;&nbsp;   2&nbsp;&nbsp;   3&nbsp;&nbsp;   4

1   5&nbsp;&nbsp;&nbsp;   6&nbsp;&nbsp;   7&nbsp;&nbsp;   8&nbsp;&nbsp;   9

2  10  11  12  13  14

3  15  16  17  18  19

4  20  21  22  23  24

&nbsp;&nbsp;   0  5  10  15  20   b   c   d   e<br>
0  1  0&nbsp;&nbsp;   0&nbsp;&nbsp;   0&nbsp;&nbsp;   0&nbsp;   1   2   3   4<br>
1  0  1&nbsp;&nbsp;   0&nbsp;&nbsp;   0&nbsp;&nbsp;   0&nbsp;   6   7   8   9<br>
2  0  0   1   0   0  11  12  13  14<br>
3  0  0   0   1   0  16  17  18  19<br>
4  0  0   0   0   1  21  22  23  24<br>

59.Obtain the column name with the highest number of row-wise maximum’s in df.

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

Column with highest row maxes:  2

60.Create a new column such that, each row contains the row number of nearest row-record by euclidean distance.

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

df

&nbsp;&nbsp;&nbsp;     p&nbsp;&nbsp;   q &nbsp;&nbsp;  r&nbsp;&nbsp;   s<br>
 a  57  77  13  62<br>
 b  68   5  92  24<br>
 c  74  40  18  37<br>
 d  80  17  39  60<br>
 e  93  48  85  33<br>
 f  69  55   8  11<br>
 g  39  23  88  53<br>
 h  63  28  25  61<br>
 i  18   4  73   7<br>
 j  79  12  45  34<br>

df

    p   q   r   s nearest_row   dist
 a  57  77  13  62           i  116.0<br>
 b  68   5  92  24           a  114.0<br>
 c  74  40  18  37           i   91.0<br>
 d  80  17  39  60           i   89.0<br>
 e  93  48  85  33           i   92.0<br>
 f  69  55   8  11           g  100.0<br>
 g  39  23  88  53           f  100.0<br>
 h  63  28  25  61           i   88.0<br>
 i  18   4  73   7           a  116.0<br>
 j  79  12  45  34           a   81.0

61.Compute maximum possible absolute correlation value of each column against other columns in df.
Input

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

Maximum Correlation possible for each column:  [ 0.91  0.57  0.55  0.71  0.53  0.26  0.91  0.71  0.69  0.71]

62.Compute the minimum-by-maximum for every row of df.

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

0    0.164835<br>
1    0.103448<br>
2    0.020202<br>
3    0.135417<br>
4    0.068182<br>
5    0.139241<br>
6    0.122449<br>
7    0.235955<br>
dtype: float64

63.Create a new column 'penultimate' which has the second largest value of each row of df.

Input

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

&nbsp;&nbsp;&nbsp;  0   1   2   3   4   5   6   7   8   9  penultimate<br>
0  52  69  62   7  20  69  38  10  57  17           62<br>
1  52  94  49  63   1  90  14  76  20  84           90<br>
2  78  37  58   7  27  41  27  26  48  51           58<br>
3   6  39  99  36  62  90  47  25  60  84           90<br>
4  37  36  91  93  76  69  86  95  69   6           93<br>
5   5  54  73  61  22  29  99  27  46  24           73<br>
6  71  65  45   9  63  46   4  93  36  18           71<br>
7  85   7  76  46  65  97  64  52  28  80           85<br>

64.    Normalize all columns of df by subtracting the column mean and divide by standard deviation.

    Range all columns of df such that the minimum value in each column is 0 and max is 1.

Don’t use external packages like sklearn.

Input

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

Solution Q1

       0     1     2     3     4     5     6     7     8     9
0  1.09  0.64 -0.33 -0.96 -1.30  0.06  0.38  1.18 -1.60  1.66<br>
1 -0.93 -2.36  0.87  1.47 -1.15  1.27  0.07 -0.87 -0.18  0.23<br>
2  1.53  0.48 -0.90  0.18 -0.33  0.81 -1.29  0.34  0.06 -0.55<br>
3  0.59 -0.24 -1.06  0.61  1.18 -1.23 -0.53 -0.45  0.34 -1.25<br>
4  0.18  0.33  1.07  1.17  0.50 -0.26 -0.25 -1.45  1.11  1.11<br>
5 -1.16  0.64 -0.93 -0.59 -0.15  0.63  1.02  1.13  1.20 -0.19<br>
6 -0.58  0.07 -0.20 -0.87 -0.22 -1.62 -1.04  0.81 -1.23 -1.04<br>
7 -0.73  0.45  1.47 -1.02  1.47  0.34  1.65 -0.71  0.31  0.02<br>

Solution Q2

       0     1     2     3     4     5     6     7     8     9
0  0.16  0.00  0.71  0.98  1.00  0.42  0.43  0.00  1.00  0.00<br>
1  0.91  1.00  0.24  0.00  0.95  0.00  0.54  0.78  0.49  0.49<br>
2  0.00  0.05  0.93  0.52  0.65  0.16  1.00  0.32  0.41  0.76<br>
3  0.35  0.29  1.00  0.35  0.10  0.86  0.74  0.62  0.31  1.00<br>
4  0.50  0.10  0.16  0.12  0.35  0.53  0.65  1.00  0.03  0.19<br>
5  1.00  0.00  0.95  0.83  0.58  0.22  0.22  0.02  0.00  0.64<br>
6  0.78  0.19  0.66  0.94  0.61  1.00  0.91  0.14  0.87  0.93<br>
7  0.84  0.06  0.00  1.00  0.00  0.32  0.00  0.72  0.32  0.56<br>

65.Compute the correlation of each row of df with its succeeding row.

Input

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;   1&nbsp;&nbsp;   2&nbsp;&nbsp;&nbsp;   3&nbsp;&nbsp;   4&nbsp;&nbsp;   5&nbsp;&nbsp;   6&nbsp;&nbsp;   7&nbsp;&nbsp;   8&nbsp;&nbsp;   9<br>
0  93  49  26   2  96  56  11  73  90  65<br>
1  54  17  47  52  65   9  21  87  94   4<br>
2  51  11  44  77  37  57  17  25  95  26<br>
3  84   8  61  43  63  63  59  65  69  29<br>
4   8  27  53  95  10  35  16  61  39  83<br>
5  30  70  91  26  12  44  37  71  21  48<br>
6  66  44  47  44  29  99  86  78  31   1<br>
7  17  40  28  12  89  95  79  54  81  47<br>

[0.40999999999999998,
 0.47999999999999998,
 0.42999999999999999,
 -0.37,
 0.23000000000000001,
 0.14000000000000001,
 0.22]

66.Replace both values in both diagonals of df with 0.

Input

df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

df

&nbsp;&nbsp;&nbsp;0   1   2   3   4   5   6   7   8   9<br>
 0  11  46  26  44  11  62  18  70  68  26<br>
 1  87  71  52  50  81  43  83  39   3  59<br>
 2  47  76  93  77  73   2   2  16  14  26<br>
 3  64  18  74  22  16  37  60   8  66  39<br>
 4  10  18  39  98  25   8  32   6   3  29<br>
 5  29  91  27  86  23  84  28  31  97  10<br>
 6  37  71  70  65   4  72  82  89  12  97<br>
 7  65  22  97  75  17  10  43  78  12  77<br>
 8  47  57  96  55  17  83  61  85  26  86<br>
 9  76  80  28  45  77  12  67  80   7  63

&nbsp;&nbsp;&nbsp;     0   1   2   3   4   5   6   7   8   9<br>
 0   0  46  26  44  11  62  18  70  68   0<br>
 1  87   0  52  50  81  43  83  39   0  59<br>
 2  47  76   0  77  73   2   2   0  14  26<br>
 3  64  18  74   0  16  37   0   8  66  39<br>
 4  10  18  39  98   0   0  32   6   3  29<br>
 5  29  91  27  86   0   0  28  31  97  10<br>
 6  37  71  70   0   4  72   0  89  12  97<br>
 7  65  22   0  75  17  10  43   0  12  77<br>
 8  47   0  96  55  17  83  61  85   0  86<br>
 9   0  80  28  45  77  12  67  80   7   0



67.This is a question related to understanding of grouped dataframe. From df_grouped, get the group belonging to 'apple' as a dataframe.

Input

df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

    col1      col2  col3
0  apple  0.673434   &nbsp;&nbsp;&nbsp;  7<br>
3  apple  0.182348   &nbsp;&nbsp; 14<br>
6  apple  0.050457    &nbsp;&nbsp;&nbsp; 3

68.In df, find the second largest value of 'taste' for 'banana'

 Input

df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

    fruit  price     taste
0   apple      7 &nbsp; 0.190229<br>
1  banana      2 &nbsp; 0.438063<br>
2  orange      1 &nbsp; 0.860182<br>
3   apple      6 &nbsp; 0.042149<br>
4  banana      2 &nbsp; 0.896021<br>
5  orange      5 &nbsp; 0.255107<br>
6   apple      6 &nbsp; 0.874533<br>
7  banana      4 &nbsp; 0.696274<br>
8  orange      9 &nbsp; 0.140713

0.69627423645996078

69.In df, Compute the mean price of every fruit, while keeping the fruit as another column instead of an index.

Input

df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

    fruit      price
0   apple  11.000000<br>
1  banana   6.333333<br>
2  orange   6.333333

70.Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.

Input

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

 	fruit	price_left	weight	pazham	pounds	price_right
0	apple	5	high	apple	high	11<br>
1	apple	10	high	apple	high	11<br>
2	apple	8	high	apple	high	11<br>
3	orange	6	low	orange	low	6<br>
4	orange	7	low	orange	low	6<br>
5	orange	0	low	orange	low	6

71.From df1, remove the rows that are present in df2. All three columns must be the same.

Input

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

    fruit  price  weight
2  banana      2     low<br>
3   apple      3    high<br>
4  orange      4  medium<br>
5  banana      5     low<br>
6   apple      6    high<br>
7  orange      7  medium<br>
8  banana      8     low<br>

72.get the positions where values of two columns match

Input

df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})


(array([1, 5, 9]),)

73.reate two new columns in df, one of which is a lag1 (shift column a down by 1 row) of column ‘a’ and the other is a lead1 (shift column b up by 1 row). Input

df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

    a   b   c   d
0  66  34  76  47<br>
1  20  86  10  81<br>
2  75  73  51  28<br>
3   1   1   9  83<br>
4  30  47  67   4

    a   b   c   d  a_lag1  b_lead1
0  66  34  76  47     NaN     86.0<br>
1  20  86  10  81    66.0     73.0<br>
2  75  73  51  28    20.0      1.0<br>
3   1   1   9  83    75.0     47.0<br>
4  30  47  67   4     1.0      NaN<br>

74.Get the frequency of unique values in the entire dataframe df.

 Input

df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

5    4<br>
4    4<br>
9    3<br>
8    2<br>
7    2<br>
3    2<br>
6    1<br>
2    1<br>
1    1<br>
dtype: int64

75.Split the string column in df to form a dataframe with 3 columns as shown. Input

df = pd.DataFrame(["STD, City    State",<br>
"33, Kolkata    West Bengal",<br>
"44, Chennai    Tamil Nadu",<br>
"40, Hyderabad    Telengana",<br>
"80, Bangalore    Karnataka"], columns=['row'])

print(df)

>                         row
> 0          STD, City\tState<br>
> 1  33, Kolkata\tWest Bengal<br>
> 2   44, Chennai\tTamil Nadu<br>
> 3  40, Hyderabad\tTelengana<br>
> 4  80, Bangalore\tKarnataka